/**
 * Generates src/app/theme.css from tonal-oklch palette definitions.
 *
 * Usage:  npm run theme
 *
 * Edit the palettes below, run the script, and the CSS file is updated.
 * The generated file is checked into git — no runtime generation needed.
 */

import { tonalOklchToResult } from "tonal-oklch";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/app/theme.css");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function hex({ tone, chroma, hue, alpha }) {
  const { hex } = tonalOklchToResult({ tone, chroma, hue });
  if (alpha != null && alpha < 1) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgb(${r} ${g} ${b} / ${alpha})`;
  }
  return hex;
}

function vars(palette) {
  return Object.entries(palette)
    .map(([key, color]) => {
      const val = hex(color);
      const { tone, chroma, hue } = color;
      const alpha = color.alpha != null ? `, alpha: ${color.alpha}` : "";
      return `  --${key}: ${val}; /* tone: ${tone}, chroma: ${chroma}, hue: ${hue}${alpha} */`;
    })
    .join("\n");
}

// ---------------------------------------------------------------------------
// Light palette — custom tokens only (shadcn tokens are in globals.css)
// ---------------------------------------------------------------------------

const light = {
  "background-popover":         { tone: 100,    chroma: 0,  hue: 0 },
  "foreground-primary":         { tone: 14,    chroma: 0,  hue: 0 },
  "foreground-secondary":       { tone: 49.83, chroma: 0,  hue: 0 },
  stroke:                       { tone: 96,    chroma: 0,  hue: 0 },
};

// ---------------------------------------------------------------------------
// Dark palette — custom tokens only (shadcn tokens are in globals.css)
// ---------------------------------------------------------------------------

const dark = {
  "background-popover":         { tone: 10,    chroma: 0,  hue: 0 },
  background:                   { tone: 8,    chroma: 0,  hue: 0 },
  "foreground-primary":         { tone: 100,   chroma: 0.01, hue: 260 },
  "foreground-secondary":       { tone: 54.57, chroma: 0,  hue: 0 },
  stroke:                       { tone: 20,    chroma: 0,  hue: 0 },
};

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

const css = `/* Generated by scripts/generate-theme.mjs — do not edit directly.
 * Source of truth: the palette objects in that script.
 * Regenerate: npm run theme
 */

:root {
${vars(light)}
}

:root.dark {
${vars(dark)}
}
`;

writeFileSync(OUT, css);
console.log(`✓ Wrote ${OUT}`);
